# Generated by Django 3.2 on 2022-03-08 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student'),
    ]

    operations = [
    ]
