# Generated by Django 3.2 on 2022-02-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Szym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('msgs', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Person',
            new_name='Krzysiem',
        ),
    ]
