# Generated by Django 3.2 on 2022-02-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_auto_20220221_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('msgs', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Krzysiem',
        ),
        migrations.DeleteModel(
            name='Szym',
        ),
    ]
