# Generated by Django 3.2 on 2022-03-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_auto_20220221_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='reakcje',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='stopy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='zdj',
            field=models.IntegerField(default=0),
        ),
    ]
