# Generated by Django 3.2 on 2022-08-29 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_alter_person_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='msgs',
        ),
        migrations.RemoveField(
            model_name='person',
            name='reakcje',
        ),
        migrations.RemoveField(
            model_name='person',
            name='stopy',
        ),
        migrations.RemoveField(
            model_name='person',
            name='zdj',
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.PositiveSmallIntegerField(default=0)),
                ('photos', models.PositiveSmallIntegerField(default=0)),
                ('reactions', models.PositiveSmallIntegerField(default=0)),
                ('feet', models.PositiveSmallIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.person')),
            ],
        ),
    ]
