# Generated by Django 3.2 on 2022-08-29 21:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_auto_20220829_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='date_from',
            field=models.DateField(default=datetime.datetime(2022, 8, 29, 21, 29, 0, 115612, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='date_to',
            field=models.DateField(default=datetime.datetime(2022, 8, 29, 21, 29, 6, 652116, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
