# Generated by Django 3.2 on 2022-03-05 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_alter_person_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='stopy',
        ),
    ]
