# Generated by Django 3.2 on 2022-03-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_remove_person_stopy'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='stopy',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
