# Generated by Django 3.2 on 2022-03-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0009_person_stopy'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='nameslug',
            field=models.SlugField(default='', max_length=30),
        ),
    ]
