# Generated by Django 3.2 on 2022-03-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0010_person_nameslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='nameslug',
            field=models.SlugField(default=models.CharField(max_length=30), max_length=30),
        ),
    ]
