# Generated by Django 3.2 on 2022-03-07 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0011_alter_person_nameslug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='nameslug',
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgs', models.PositiveSmallIntegerField(default=0)),
                ('zdj', models.PositiveSmallIntegerField(default=0)),
                ('reakcje', models.PositiveSmallIntegerField(default=0)),
                ('stopy', models.PositiveSmallIntegerField(default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.person')),
            ],
        ),
    ]
