# Generated by Django 3.2 on 2022-03-07 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0012_auto_20220307_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='msgs',
        ),
        migrations.RemoveField(
            model_name='person',
            name='reakcje',
        ),
        migrations.RemoveField(
            model_name='person',
            name='stopy',
        ),
        migrations.RemoveField(
            model_name='person',
            name='zdj',
        ),
    ]
