# Generated by Django 3.2 on 2022-03-08 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0013_auto_20220307_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=False),
            preserve_default=False,
        ),
    ]
