# Generated by Django 3.2 on 2022-03-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0016_remove_person_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.SlugField(default='a'),
        ),
    ]
